add async job and test
Joannitka-pl/monte-cinema pull request #6
Opened 2021-05-31 20:45 UTC by Joannitka-pl

Added async job for reservation timeout at offline ticket desk so two ticket desks cannot sell the same ticket at the same time.

2021-06-01 06:47 UTC, tobiaszwaszak commented on app/concepts/reservations/use_cases/create.rb
> +        ReservationTimeoutJob.set(wait: 10.minutes).perform_later(reservation)
you don't have `reservation`
if you want to use it you have to assign it `reservation = repository.create(params)`
but in this case, you will not return the reservation (you have to add it in last line of method call)
and, you don't have `ticket_desk here`

2021-06-01 06:47 UTC, tobiaszwaszak commented on app/jobs/reservation_timeout_job.rb
> +    Reservations::UseCases::Destroy.new.call(id: params[:id])
you don't have params here

2021-06-01 06:47 UTC, tobiaszwaszak commented on config/routes.rb
> +  require 'sidekiq/web'
require should be on the top

2021-06-01 06:47 UTC, tobiaszwaszak commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
something like that you should test in `concepts/reservations/use_cases/create_spec.rb`
in this test, you could do something like

```
it do
    described_class.new.perform(reservation)
    expect(Reservations::UseCases::Destroy).to have_received(:call)
 end
```

2021-06-01 13:34 UTC, Joannitka-pl commented on app/concepts/reservations/use_cases/create.rb
> +        ReservationTimeoutJob.set(wait: 10.minutes).perform_later(reservation)
after consultation with @wmaciejak we have come to the conclusion to put `reservation = repository.create(params)` in the beginning of the method `call` to be able to access reservation.id.

2021-06-01 13:35 UTC, Joannitka-pl commented on config/routes.rb
> +  require 'sidekiq/web'
- [ ]

2021-06-01 13:37 UTC, Joannitka-pl commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
Unfortunately this test doesn't pass. Not sure why? The error message says: undefined local variable or method 'reservation_id' for... create_spec.rb.7.

2021-06-01 13:43 UTC, tobiaszwaszak commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
hard to say, you didn't push changes

2021-06-01 13:49 UTC, Joannitka-pl commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
They're here:
https://github.com/Joannitka-pl/monte-cinema/pull/6/commits/908e4c5818b5d70ad985c3975eff169284b5afcc 
I can see this commit below our discussion.

2021-06-01 13:55 UTC, tobiaszwaszak commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
you have to assign something as a reservation_id
or create a reservation and use reservation.id

2021-06-02 14:24 UTC, Joannitka-pl commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
still not working when testing with Rspec...

2021-06-02 14:28 UTC, Joannitka-pl commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
<img width="764" alt="Screenshot 2021-06-02 at 16 05 24" src="https://user-images.githubusercontent.com/58233783/120498493-8d328400-c3bf-11eb-9a1f-492834f81328.png">

2021-06-02 14:32 UTC, wmaciejak commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
Could you please push your latest changes to this branch?

2021-06-02 15:19 UTC, Joannitka-pl commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
I have pushed it already and can see corresponding commit below our chat. 
Here: https://github.com/Joannitka-pl/monte-cinema/pull/6/commits/01a63f24a210391b3226c45ab3baa85b0a45bf2d 
Am I doing it wrong?

2021-06-02 16:16 UTC, wmaciejak commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
I missed it probably or I looked into wrong files, sorry :)

2021-06-07 07:55 UTC, Joannitka-pl commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
@wmaciejak Hey, have you had a chance to look into it?

2021-06-07 08:07 UTC, wmaciejak requested changes

2021-06-07 08:07 UTC, wmaciejak commented on spec/jobs/reservation_timeout_job_spec.rb
> +        ReservationTimeoutJob.perform_later('reservation')
Please check this comment
https://github.com/Joannitka-pl/monte-cinema/pull/6#discussion_r644127950

2021-06-18 10:56 UTC, closed without merging