troubles with adding online reservation
Joannitka-pl/monte-cinema pull request #9
Opened 2021-06-08 20:02 UTC by Joannitka-pl

"status": 500,
    "error": "Internal Server Error",
    "exception": "#<NoMethodError: undefined method `each' for nil:NilClass>",
    "traces": {
        "Application Trace": [
            {
                "exception_object_id": 726940,
                "id": 0,
                "trace": "app/concepts/tickets/use_cases/create.rb:12:in `call'"

2021-06-09 10:25 UTC, Joannitka-pl commented on app/concepts/tickets/use_cases/create.rb
> +        tickets.each do |ticket|
That's right, thank you! :)

2021-06-09 10:49 UTC, Sonickers commented on app/concepts/reservations/use_cases/create_reservation_with_tickets.rb
> +          @reservation = @repository.create(reservation_params)
Does it work as you wanted? I might be wrong but probably you are missing "!" in you "create" method - if something went wrong with reservation it will just return _false_ but it won't exit your transaction with the error

2021-06-09 12:28 UTC, Joannitka-pl commented on app/concepts/reservations/use_cases/create_reservation_with_tickets.rb
> +          @reservation = @repository.create(reservation_params)
That's true. Thank you :)

2021-06-10 16:32 UTC, Sonickers commented on app/concepts/tickets/representers/single.rb
> +        Reservations::Representers::List.new(ticket).basic
Could you explain how this is suppose to work?

2021-06-10 16:40 UTC, Sonickers commented on app/concepts/tickets/use_cases/create.rb
> +        @reservation.seat.split(', ').each do |seat|
Maybe once again consider this other option we talked about (with .map(&:strip), because you don't have to worry if something went wrong and you get a string without spaces (you can check it in irb)

2021-06-10 17:11 UTC, kodowicz requested changes

2021-06-10 17:11 UTC, kodowicz commented on lib/base_repository.rb
> +  def create!(params)
You should add a bang to create like this: `adapter.create!(params)`. You are naming the method with the exclamation point to tell others this method will call `create!` and raise the error if record is not created

2021-06-10 19:18 UTC, agusiol commented on app/concepts/tickets/use_cases/create.rb
> +            @reservation.tickets.create!(ticket_params)
Are you using this `|seat|` anywhere here? Or is it just for number of Tickets that you want to create?

2021-06-10 19:28 UTC, agusiol commented on app/concepts/tickets/use_cases/create.rb
> +        @reservation.seat.split(', ').each do |seat|
Could you tell me what' `@reservation.seat`returns? Because looking at seeds it is one seat per reservation?

2021-06-11 08:09 UTC, Joannitka-pl commented on app/concepts/tickets/use_cases/create.rb
> +        @reservation.seat.split(', ').each do |seat|
Sure, I was thinking what is the difference between those two approaches. Will do that, thank you :)

2021-06-15 15:16 UTC, Joannitka-pl commented on lib/base_repository.rb
> +  def create!(params)
thank you 🙏

2021-06-16 13:52 UTC, merged